/* Generated by AN DISI Unibo */ 
package it.unibo.ctxConsoleAnalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxConsoleAnalysis  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxConsoleAnalysis";
	return QActorContext.initQActorSystem(
		"ctxconsoleanalysis", "./srcMore/it/unibo/ctxConsoleAnalysis/robotroomba.pl", 
		"./srcMore/it/unibo/ctxConsoleAnalysis/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
