/* Generated by AN DISI Unibo */ 
package it.unibo.consoleanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Consoleanalysis extends QActorMsgQueue{
	public MsgHandle_Consoleanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
