/* Generated by AN DISI Unibo */ 
package it.unibo.virtualrobotexecutor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Virtualrobotexecutor extends QActorMsgQueue{
	public MsgHandle_Virtualrobotexecutor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
