/* Generated by AN DISI Unibo */ 
package it.unibo.testanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testanalysis extends QActorMsgQueue{
	public MsgHandle_Testanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
