/* Generated by AN DISI Unibo */ 
package it.unibo.delegateexecutor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Delegateexecutor extends QActorMsgQueue{
	public MsgHandle_Delegateexecutor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
