/* Generated by AN DISI Unibo */ 
package it.unibo.mindrobotanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mindrobotanalysis extends QActorMsgQueue{
	public MsgHandle_Mindrobotanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
