/* Generated by AN DISI Unibo */ 
package it.unibo.testmockledanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testmockledanalysis extends QActorMsgQueue{
	public MsgHandle_Testmockledanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
