/* Generated by AN DISI Unibo */ 
package it.unibo.mindrobot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mindrobot extends QActorMsgQueue{
	public MsgHandle_Mindrobot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
