/* Generated by AN DISI Unibo */ 
package it.unibo.ledmockledanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledmockledanalysis extends QActorMsgQueue{
	public MsgHandle_Ledmockledanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
