/* Generated by AN DISI Unibo */ 
package it.unibo.realrobotexecutor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Realrobotexecutor extends QActorMsgQueue{
	public MsgHandle_Realrobotexecutor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
