/* Generated by AN DISI Unibo */ 
package it.unibo.robotanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robotanalysis extends QActorMsgQueue{
	public MsgHandle_Robotanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
