/* Generated by AN DISI Unibo */ 
package it.unibo.robotexecutormockledanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robotexecutormockledanalysis extends QActorMsgQueue{
	public MsgHandle_Robotexecutormockledanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
