/* Generated by AN DISI Unibo */ 
package it.unibo.robotexecutor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robotexecutor extends QActorMsgQueue{
	public MsgHandle_Robotexecutor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
