/* Generated by AN DISI Unibo */ 
package it.unibo.mindrobotmockledanalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mindrobotmockledanalysis extends QActorMsgQueue{
	public MsgHandle_Mindrobotmockledanalysis(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
